---
- name: Basic ASPP laptop setup
  hosts: all

  roles:
    - ansible-pull
    - common

- name: ASPP user setup
  hosts: all

  remote_user: root
  become_user: student
  become: true

  roles:
    - user-setup

- name: ASPP bonus setup
  hosts: all

  roles:
    - role: music-setup
      tags:
        - music-setup
    - role: chatgpt-guard
      tags:
        - chatgpt-guard
