---
# Full ASPP laptop setup with enabled+started ansible-pull timers

- name: Basic ASPP laptop setup
  hosts: all
  tags: stage-basic

  roles:
    - role: ansible-pull
      vars:
        ansible_pull_timer_enabled: true
        ansible_pull_timer_started: true
    - network
    - common

- name: ASPP user setup
  hosts: all
  tags: stage-user

  remote_user: root
  become_user: student
  become: true

  roles:
    - user-setup

- name: ASPP bonus setup
  hosts: all
  tags: stage-bonus

  roles:
    - role: music-setup
      tags:
        - music-setup
    - role: chatgpt-guard
      tags:
        - chatgpt-guard
