---
# Full ASPP laptop setup with enabled+started ansible-pull timers

- name: Basic ASPP laptop setup
  hosts: all
  tags: stage-basic

  roles:
    - role: ansible_pull
      vars:
        ansible_pull_timer_enabled: true
        ansible_pull_timer_started: true
    - network
    - common

- name: ASPP user setup
  hosts: all
  tags: stage-user

  remote_user: root
  become_user: student
  become: true

  roles:
    - user_setup

- name: ASPP bonus setup
  hosts: all
  tags: stage-bonus

  roles:
    - role: music_setup
      tags:
        - music-setup
    - role: chatgpt_guard
      tags:
        - chatgpt-guard
