# ansible-pull setup
#
# on remote hosts, set up ansible to run periodically using the latest code
# from a particular checkout, in pull based fashion, inverting Ansible's
# usual push-based operating mode.
---

- hosts: all
  remote_user: root

  vars:
    schedule: |
      OnBootSec=20 s
      OnUnitInactiveSec=10 min
      RandomizedDelaySec=30 s

    repo_url: https://github.com/aspp/installation

    pull_tags: packages,remote

  tasks:
    - name: Install ansible
      apt:
        name: ansible,git
        force_apt_get: yes
      tags: packages

    - name: Create unit directory
      file:
        path: /usr/local/lib/systemd/system/
        state: directory

    - name: Install timer file
      copy:
        dest: /usr/local/lib/systemd/system/ansible-pull.timer
        content: |
          [Timer]
          {{ schedule }}

          [Install]
          WantedBy=default.target

    - name: Install service file
      copy:
        dest: /usr/local/lib/systemd/system/ansible-pull.service
        content: |
          [Service]
          Type=oneshot
          ExecStart=ansible-pull -i localhost, -U {{ repo_url }} --only-if-changed -t {{ pull_tags }} all.yml

    - name: Enable timer
      systemd:
        name: ansible-pull.timer
        enabled: true
        state: started
        daemon_reload: yes
