---

- hosts: all
  remote_user: root

  vars:
    repo_url: https://github.com/keszybz/redirect

  tasks:
    - name: Clone ChatGPT-Guard repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: /srv/chatgpt-guard
      tags: packages,remote

    - name: Enable ChatGPT-Guard units
      ansible.builtin.command:
        cmd: /srv/chatgpt-guard/do_setup.sh
        creates: /etc/systemd/system/chatgpt-guard.socket
      tags: packages,remote
