---
  - name: Music setup
    remote_user: root
    hosts: all
    tasks:
      - name: Copy music folder
        copy:
          src: 'files/music/'
          dest: '/home/student/.music/'
        tags: remote

      - name: Set up timers
        copy:
          src: 'files/music/aspp-music-finalcountdown.service'
          dest: '/etc/systemd/system/'
        tags: remote

      - name: Set up timers
        copy:
          src: 'files/music/aspp-music-finalcountdown.timer'
          dest: '/etc/systemd/system/'
        tags: remote

      - name: Set up timers
        copy:
          src: 'files/music/aspp-music-pushit.service'
          dest: '/etc/systemd/system/'
        tags: remote

      - name: Set up timers
        copy:
          src: 'files/music/aspp-music-pushit.timer'
          dest: '/etc/systemd/system/'
        tags: remote

      - command: /usr/bin/systemctl daemon-reload
        tags: remote

      - name: Enable music
        ansible.builtin.systemd:
          name: aspp-music-pushit.timer
          state: started
        tags: remote

      - name: Enable music
        ansible.builtin.systemd:
          name: aspp-music-finalcountdown.timer
          state: started
        tags: remote

