---
  - name: Provision Software
    remote_user: root
    hosts: all
    tasks:
      - name: Add git ppa
        tags: packages
        when: ansible_distribution == "Ubuntu"
        apt_repository:
          repo: 'ppa:git-core/ppa'
          state: present

      - name: Disable apt autoupdates
        tags: remote
        when: ansible_distribution == "Ubuntu"
        copy:
          content: |
             APT::Periodic::Update-Package-Lists "0";
             APT::Periodic::Unattended-Upgrade "0";

          dest: /etc/apt/apt.conf.d/20auto-upgrades

      - name: Disable apt-daily.timer
        tags: remote
        when: ansible_distribution == "Ubuntu"
        ansible.builtin.systemd:
          name: apt-daily.timer
          state: stopped
          enabled: false

      - name: Disable apt-daily service
        tags: remote
        when: ansible_distribution == "Ubuntu"
        ansible.builtin.systemd:
          name: apt-daily.service
          state: stopped
          enabled: false

      - name: Install essential distro packages (Ubuntu)
        apt:
          name: "{{ packages }}"
          update_cache: yes
          force_apt_get: yes
        tags: packages
        when: ansible_distribution == "Ubuntu"
        vars:
          packages:
            - git
            - gitg
            - gitk
            - git-doc
            - git-gui
            - git-email
            - tig
            - tmux
            - emacs
            - vim
            - micro
            - curl
            - python3-psutil  # for ansible
            - openssh-server
            - gcc
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - flex
            - bison
            - gdb
            - gcc-doc
            - inkscape
            - geeqie
            - graphviz
            - graphviz-doc
            - liblz4-tool
            - firefox
            - kcachegrind
            - gnome-builder
            - gedit
            - gedit-plugins
            - htop
            - curl
            - ncdu
            - moreutils
            - cython3
            - debian-archive-keyring
            - gpg
            - hwloc
            - tmux
            - python-is-python3
            - python3-pip
            - python3-numpy
            - python3-scipy
            - python3-zmq
            - python3-yaml
            - python3-pytest
            - python3-colorama
            - python3-networkx
            - ipython3
            - python3-dask
            - python3-graphviz
            - python3-mpltoolkits.basemap
            - python3-distributed
            - python3-coverage
            - python3-line-profiler
            - python3-memory-profiler
            - python3-bcolz
            - python3-plotly
            - python3-opencv
            - python3-toolz
            # - python3-joblib
            - python3-sklearn
            - python3-sklearn-pandas
            - python3-scipy
            - python3-matplotlib
            - python3-matplotlib-venn
            - python3-willow
            - python3-pyflakes
            - python3-sphinx
            - python3-sphinx-rtd-theme
            - python3-pytest
            - python3-pytest-pep8
            - python3-pytest-pylint
            - python3-pytest-cov
            - python3-mpi4py
            - python3-imageio
            - python3-h5py
            - python3-skimage
            - python3-tweepy
            - python3-xlrd
            - python3-seaborn
            - python3-venv
            - cufflinks
            - runsnakerun
            - libopenblas-base
            - libopenblas-dev
            - flite
            # - bloscpack
            - jupyter-client
            - jupyter-console
            - jupyter-notebook
            - jupyter-nbconvert
            - jupyter-qtconsole
            - python3-ipython

            # For pelita testing
            - xauth

            # In case gnome is weird, the tweak tool may help in adjusting hidden settings
            - gnome-tweak-tool

            # Optional timers for the status bar (can be helpful for pair-programming)
            - gnome-shell-pomodoro
            - gnome-shell-timer

      - name: Remove updater packages (Ubuntu)
        apt:
          name: "{{ packages }}"
          update_cache: yes
          force_apt_get: yes
          state: absent
        tags: packages
        when: ansible_distribution == "Ubuntu"
        vars:
          packages:
            - update-notifier
            - update-manager

      - name: Install distro packages (Fedora)
        dnf:
          name: "{{ packages }}"
        tags: packages
        when: ansible_distribution == "Fedora"
        vars:
          packages:
            - sudo
            - plocate
            - gcc
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - flex
            - bison
            - gdb
            - strace
            - ltrace
            - fpaste
            - man-db
            - dstat
            # - gcc-doc
            - openssh-clients
            - openssh-server
            - lz4
            - git
            - gitg
            - gitk
            - git-core-doc
            - git-gui
            - git-email
            - tig
            - gprof2dot
            - emacs
            - vim
            - htop
            - curl
            - ncdu
            - micro
            - meson
            - moreutils
            - curl
            - python3-Cython
            - gnupg2
            - hwloc
            - tmux
            - bash-completion
            - bind-utils
            - python3-ara
            - python3-numpy
            - python3-scipy
            - python3-blosc
            - python3-zmq
            - python3-yaml
            - python3-colorama
            - python3-networkx
            - python3-jupyter-client
            - python3-jupyter-console
            - python3-jupyter-c-kernel
            - python3-jupyter-sphinx
            - python3-ipython
            - python3-pytest
            - python3-dask
            - python3-dask+array
            - python3-dask+bag
            - python3-dask+dataframe
            - python3-dask+delayed
            - python3-dask+diagnostics
            - python3-GitPython
            - python3-graphviz
            # - python3-mpltoolkits.basemap
            - python3-coverage
            # - python3-line-profiler
            # - python3-memory-profiler
            # - python3-bcolz
            - python3-pip
            - python3-plotly
            - python3-opencv
            - python3-toolz
            - python3-joblib
            - python3-scikit-learn
            - python3-scipy
            - python3-matplotlib
            # - python3-matplotlib-venn
            # - python3-willow
            - python3-pyflakes
            - python3-sphinx
            - python3-sphinx_rtd_theme
            - python3-pudb
            - python3-pytest
            - python3-pytest-flake8
            - python3-pytest-flakes
            - python3-pytest-mpi
            - python3-pytest-cov
            - python3-mpi4py-mpich
            - python3-mpi4py-openmpi
            - python3-imageio
            - python3-h5py
            - python3-scikit-image
            # - python3-tweepy
            - python3-xlrd
            - python3-seaborn
            - python3-psutil
            # - cufflinks
            # - runsnakerun
            # - libopenblas-base: we probably want to pull in all blas implementations
            #                     and provide instructions how to switch using flexiblas.
            - flexiblas-devel
            - flite
            # - bloscpack

            # Installed using pip in Ubuntu
            - python3-pandas
            - python3-bokeh
            - python3-pysnooper
            - python3-ipyparallel

            # For pelita testing
            - xauth

      - name: Install distro packages (Fedora)
        dnf:
          name: "{{ packages }}"
        tags: packages, graphical
        when: ansible_distribution == "Fedora"
        vars:
          packages:
            # Desktop
            - '@gnome-desktop'
            - gnome-shell-extension-appindicator
            - gnome-shell-extension-background-logo
            - gnome-shell-extension-caffeine
            - gnome-shell-extension-dash-to-dock
            - gnome-shell-extension-launch-new-instance
            - gnome-shell-extension-openweather
            - gnome-shell-extension-workspace-indicator

            # Various
            - inkscape
            - geeqie
            - graphviz
            - graphviz-doc
            - openssh-askpass
            - xclip
            - firefox
            - kcachegrind
            - gnome-builder
            - gedit
            - gedit-plugins

            # Fonts
            - google-noto-*

      - name: Install latest git
        tags: packages
        when: ansible_distribution == "Ubuntu"
        apt:
          name: git
          state: latest
          force_apt_get: yes

      - name: Install desktop
        tags: packages
        when: ansible_distribution == "Ubuntu"
        apt:
          name: ubuntu-desktop
          # Doesn't work with ansible 2.7 in Ubuntu 19.04
          # policy_rc_d: 101
          force_apt_get: yes

      - stat:
          path: /usr/bin/atom
        tags: packages,atom,graphical
        register: atom_exists
      - name: Install atom
        tags: packages,atom,graphical
        when: not atom_exists.stat.exists and ansible_distribution == "Ubuntu"
        apt:
          deb: https://atom.io/download/deb
          #deb: http://10.5.7.35:8000/deb
          force_apt_get: yes
        ignore_errors: yes
      - name: Install atom
        tags: packages,atom,graphical
        when: not atom_exists.stat.exists and ansible_distribution == "Fedora"
        dnf:
          name: https://github.com/atom/atom/releases/download/v1.60.0/atom.x86_64.rpm
          disable_gpg_check: yes

      - stat:
          path: /usr/bin/code
        tags: packages,visualstudio,graphical
        register: code_exists
      - name: Install visualstudio code
        tags: packages,visualstudio,graphical
        when: not code_exists.stat.exists and ansible_distribution == "Ubuntu"
        apt:
          deb: https://go.microsoft.com/fwlink/?LinkID=760868
          force_apt_get: yes
      - name: Install visualstudio code
        tags: packages,visualstudio,graphical
        when: not code_exists.stat.exists and ansible_distribution == "Fedora"
        dnf:
          name: https://packages.microsoft.com/yumrepos/vscode/code-1.70.2-1660629488.el7.x86_64.rpm
          disable_gpg_check: yes
