---
  - name: Enable/disable Services
    remote_user: root
    hosts: all
    tasks:
      - name: Enable timesyncd
        tags: remote
        when: ansible_distribution == "Fedora"
        ansible.builtin.systemd:
          name: systemd-timesyncd.service
          state: started
          enabled: true

      - name: Disable packagekit.service
        tags: remote
        when: ansible_distribution == "Fedora"
        ansible.builtin.systemd:
          name: packagekit.service
          state: stopped
          masked: true
          enabled: false
        ignore_errors: yes

      - name: Disable packagekit-offline-update.service
        tags: remote
        when: ansible_distribution == "Fedora"
        ansible.builtin.systemd:
          name: packagekit-offline-update.service
          state: stopped
          masked: true
          enabled: false
        ignore_errors: yes
