---
  - name: Enable/disable Services
    remote_user: root
    hosts: all
    tasks:
      - name: Disable packagekit.service manually
        ansible.builtin.file:
          src: /dev/null
          dest: /etc/systemd/system/packagekit.service
          state: link

      - name: Disable packagekit-offline-update.service manually
        ansible.builtin.file:
          src: /dev/null
          dest: /etc/systemd/system/packagekit-offline-update.service
          state: link

      - name: Disable packagekit.service
        tags: remote
        when: ansible_distribution == "Fedora"
        ansible.builtin.systemd:
          name: packagekit.service
          state: stopped
          masked: true
          enabled: false
        ignore_errors: yes

      - name: Disable packagekit-offline-update.service
        tags: remote
        when: ansible_distribution == "Fedora"
        ansible.builtin.systemd:
          name: packagekit-offline-update.service
          state: stopped
          masked: true
          enabled: false
        ignore_errors: yes

      - name: Enable growfs-root.service manually
        tags: remote
        when: ansible_distribution == "Fedora"
        ansible.builtin.file:
          src: /usr/lib/systemd/system/growfs-root.service
          dest: /etc/systemd/system/sysinit.target.wants/growfs-root.service
          state: link
