---
  - name: Create student user
    remote_user: root
    vars_files:
      - passwords.yml
    hosts: all
    tasks:
      - name: Create student user
        when: ansible_distribution == "Ubuntu"
        user:
          name: student
          comment: ASPP Student
          groups: adm, sudo
          password: "{{ student_password }}"
          shell: "/bin/bash"
        tags: user-creation

      - name: Create student user
        when: ansible_distribution == "Fedora"
        user:
          name: student
          comment: ASPP Student
          groups: adm, wheel
          password: "{{ student_password }}"
          shell: "/bin/bash"
        tags: user-creation

      - name: Set authorized key
        authorized_key:
          user: student
          state: present
          key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAEgEXiWzskC+g+5Va0qtiLi3yiT1UL+ENruRwEgX5FnlknJuKE7NM+6LYccG4MKlgjymbQKN02L7g4E/FRJPJk= student@aspp"
          exclusive: no
        ignore_errors: yes
        tags: user-creation

      - name: Allow password authentication (Fedora)
        when: ansible_distribution == "Fedora"
        tags: user-creation
        copy:
          content: |
             PasswordAuthentication yes

          dest: /etc/ssh/sshd_config.d/80-password-auth.conf

      - name: Allow X forwarding (Fedora)
        when: ansible_distribution == "Fedora"
        tags: user-creation
        copy:
          content: |
             ForwardX11 yes

          dest: /etc/ssh/ssh_config.d/80-x-forwarding.conf

      - name: Reload sshd config
        tags: user-creation
        ansible.builtin.systemd:
          name: sshd.service
          state: reloaded

      - name: Set up autologin
        when: ansible_distribution == "Ubuntu"
        copy:
          src: files/custom.conf
          dest: /etc/gdm3/
        tags: user-creation

      - name: Set up autologin
        when: ansible_distribution == "Fedora"
        copy:
          src: files/custom.conf
          dest: /etc/gdm/
        tags: user-creation

      - name: Setup /etc/firefox/sysprefs.js
        copy:
          src: files/sysprefs.js
          dest: /etc/firefox/
        tags: remote

      - name: Set timezone to Europe/Madrid
        timezone:
          name: Europe/Rome
        tags: remote

      - name: Set language to English
        copy:
          content: |
            LANG=en_US.UTF-8
          dest: /etc/locale.conf
        tags: remote

      - name: Set language to English
        copy:
          content: |
            LANG=en_US.UTF-8
          dest: /etc/default/locale
        tags: remote
        when: ansible_distribution == "Ubuntu"
