---
# Sadly Python doesn't want to support default password hashing methods anymore in the stdlib:
# https://bugs.python.org/issue44309, let's use whois instead.
#
# echo password | mkpasswd -m yescrypt --stdin
#         student
student_password: "$y$j9T$9zvGwkFhHinxNiVUcQqlo.$yeu5cJDJAJSTING.AR8khCpBFlJ.16eGrkfOFuLoBj7"
has_vscode: False
has_vscodium: True

