---
# Sadly Python doesn't want to support default password hashing methods anymore in the stdlib:
# https://bugs.python.org/issue44309, let's use whois instead.
#
# echo password | mkpasswd -m yescrypt --stdin
#         student
common_student_password: "$y$j9T$9zvGwkFhHinxNiVUcQqlo.$yeu5cJDJAJSTING.AR8khCpBFlJ.16eGrkfOFuLoBj7"
common_itbguest_password: "$y$j9T$K9P3UjgNmL9H9Lvmc3q601$Jv8CGSkJya6wkXkbHYCxBd39c9O1THUn4ugpG1lnaY3"
common_has_vscode: false
common_has_vscodium: true

common_timezone: Europe/Berlin
