---
# Sadly Python doesn't want to support default password hashing methods anymore in the stdlib:
# https://bugs.python.org/issue44309, let's use whois instead.
#
# echo password | mkpasswd -m yescrypt --stdin
#         student
common_student_password: "$y$j9T$9zvGwkFhHinxNiVUcQqlo.$yeu5cJDJAJSTING.AR8khCpBFlJ.16eGrkfOFuLoBj7"
common_has_vscode: false
common_has_vscodium: true
