#!/bin/bash
set -xeuo pipefail

[ "$1" = "final" ] || exit 0

mkosi-chroot git clone --depth 1 https://github.com/ASPP/installation /root/installation

# This does not enable the ansible timers.
# If this is desired use the second playbook in the VM or run mkosi build --profile enable_timers

mkosi-chroot ansible-playbook -i localhost, --connection local /root/installation/setup-ansible.yml

# ansible-playbook -i localhost, --connection local /root/installation/setup-ansible.yml -e ansible_pull_timer_enabled=True
