---
ansible_pull_schedule_init: |
  OnBootSec=30 s
  OnUnitInactiveSec=1 h
  RandomizedDelaySec=30 s

ansible_pull_schedule_repeat: |
  OnBootSec=5 min
  OnUnitInactiveSec=5 min
  RandomizedDelaySec=30 s
