# ansible-pull setup
#
# on remote hosts, set up ansible to run periodically using the latest code
# from a particular checkout, in pull based fashion, inverting Ansible's
# usual push-based operating mode.
---
- name: Install ansible
  dnf:
    name: ansible, git, dbus-tools, python3-ara
  tags: packages

- name: Create unit directory
  file:
    path: /usr/local/lib/systemd/system/
    state: directory
  tags: config

- name: Install ansible-pull timers
  ansible.builtin.template:
    dest: "/usr/local/lib/systemd/system/{{ item }}"
    src: "{{ item }}.j2"
    owner: root
    group: root
    mode: '0644'
  tags: config
  loop:
  - ansible-pull-init.timer
  - ansible-pull-init.service
  - ansible-pull-repeat.timer
  - ansible-pull-repeat.service

- name: Create override folder for ansible-pull-.service
  file:
    path: /usr/local/lib/systemd/system/ansible-pull-.service.d
    state: directory
  tags: config

- name: Add ara config to ansible-pull-
  ansible.builtin.template:
    dest: "/usr/local/lib/systemd/system/ansible-pull-.service.d/ara.conf"
    src: "ara.conf.j2"
    owner: root
    group: root
    mode: '0644'
  tags: config

- name: Daemon reload
  # Manually reloading and ignoring the errors
  # That way it will not fail if we are running mkosi shell
  command: systemctl daemon-reload
  ignore_errors: True

- name: Enable ansible-pull timers
  tags: config
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: "{{ ansible_pull_timer_enabled }}"
  loop:
  - ansible-pull-init.timer
  - ansible-pull-repeat.timer

- name: Start ansible-pull timers
  tags: config
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: "started"
  loop:
  - ansible-pull-init.timer
  - ansible-pull-repeat.timer
  when: ansible_pull_timer_started

