---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Create ASPP user
  ansible.builtin.import_tasks: users.yml

- name: Start services
  ansible.builtin.import_tasks: services.yml
