---
- name: Install basic system packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
  tags: packages
  vars:
    packages:
      - acl
      - sudo
      - plocate
      - zram-generator-defaults
      - diffutils
      - "@c-development"
      - meson
      - fpaste
      - rsync
      - man-db
      - openssh-clients
      - openssh-server
      - git
      - gitg
      - gitk
      - git-gui
      - tig
      - emacs
      - vim-enhanced
      - neovim
      - python3-neovim
      - fzf
      - fd-find
      - htop
      - curl
      - micro

      - moreutils

      - python3-cython

      - hwloc
      - tmux
      - bash-completion

      - python3-ara # needed for ARA Ansible monitoring


      - python3-numpy
      - python3-scipy
      - python3-zmq
      - python3-yaml
      - python3-colorama
      - python3-networkx
      - python3-jupyter-client
      - python3-jupyter-console
      - python3-ipython
      - python3-pytest

      - python3-pip
      - python3-scipy
      - python3-matplotlib
      - python3-pytest
      - python3-uv
      - flexiblas-devel
      - flite
      - python3-pandas

      # For ansible settings
      - dconf
      - dbus-daemon

      - mpv
      - alsa-utils
      - python3-systemd

- name: Install desktop and supplementary packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
  tags: packages, graphical-packages
  vars:
    packages:
      # Desktop
      - "@gnome-desktop"
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-openweather
      - gnome-shell-extension-workspace-indicator

      # Various
      - inkscape
      - geeqie # image viewer
      - graphviz
      - graphviz-doc
      - openssh-askpass
      - xclip
      - firefox
      - gedit
      - gedit-plugins
      - geany

      # Fonts for the pacman characters on the command line
      - google-noto-sans-canadian-aboriginal-fonts
      - google-noto-sans-canadian-aboriginal-vf-fonts
      - google-noto-emoji-color-fonts

# - name: Install ASPP software packages

- name: Install VSCode
  ansible.builtin.import_tasks: packages_vscode.yml
  when: common_has_vscode

- name: Install VSCodium
  ansible.builtin.import_tasks: packages_vscodium.yml
  when: common_has_vscodium

- name: Install pre-compiled py-spy
  tags: packages
  ansible.builtin.copy:
    src: files/py-spy
    mode: "0755"
    dest: /usr/local/bin/
