---
- name: Create student user
  user:
    name: student
    comment: ASPP Student
    groups: adm, wheel
    password: "{{ student_password }}"
    shell: "/bin/bash"
  tags: user-creation

- name: Set authorized key
  authorized_key:
    user: student
    state: present
    key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAEgEXiWzskC+g+5Va0qtiLi3yiT1UL+ENruRwEgX5FnlknJuKE7NM+6LYccG4MKlgjymbQKN02L7g4E/FRJPJk= student@aspp"
    exclusive: false
  ignore_errors: true
  tags: user-creation

- name: Allow password authentication (Fedora)
  tags: user-creation
  copy:
    content: |
      PasswordAuthentication yes

    dest: /etc/ssh/sshd_config.d/80-password-auth.conf

- name: Allow X forwarding (Fedora)
  tags: user-creation
  copy:
    content: |
      ForwardX11 yes

    dest: /etc/ssh/ssh_config.d/80-x-forwarding.conf

- name: Reload sshd config
  tags: user-creation
  ansible.builtin.systemd_service:
    name: sshd.service
    state: reloaded

- name: Set up autologin
  copy:
    src: gdm-custom.conf
    dest: /etc/gdm/
  tags: user-creation

- name: Create firefox preferences directory
  file:
    path: /usr/lib64/firefox/browser/defaults/preferences/
    state: directory
  tags: remote

- name: Setup firefox homepage
  copy:
    content: |
      pref("browser.startup.homepage", "data:text/plain,browser.startup.homepage=https://aspp.school/wiki/schedule");

    dest: /usr/lib64/firefox/browser/defaults/preferences/firefox-aspp.js

  tags: remote

- name: Set timezone to Europe/Athens
  timezone:
    name: Europe/Athens
  tags: remote

- name: Set language to English
  copy:
    content: |
      LANG=en_US.UTF-8
    dest: /etc/locale.conf
  tags: remote

- name: Create local unit directory
  file:
    path: /usr/local/lib/systemd/user/
    state: directory
  tags: remote

- name: Install keyadder service
  copy:
    dest: /usr/local/lib/systemd/user/keyadder@.service
    content: |
      [Unit]
      BindsTo=%i.mount

      [Service]
      ExecStart=sh -x -c 'for i in %f/id_*.pub; do ssh-add - <$${i%%.pub}; done'
      ExecStop=ssh-add -D

      Type=oneshot
      RemainAfterExit=true

  tags: remote

- name: Create local unit directory
  file:
    path: /usr/local/lib/systemd/user/run-media-.mount.d
    state: directory
  tags: remote

- name: Install keyadder service
  copy:
    dest: /usr/local/lib/systemd/user/run-media-.mount.d/keyadder.conf
    content: |
      [Unit]
      Wants=keyadder@%N.service

  tags: remote

- name: Install Wifi connection profile
  copy:
    src: files/FORTH_Guests.nmconnection
    dest: /etc/NetworkManager/system-connections/
  tags: remote
