---
- name: Create student user
  tags: user-creation
  ansible.builtin.user:
    name: student
    comment: ASPP Student
    groups: adm, wheel
    password: "{{ common_student_password }}"
    shell: "/bin/bash"

- name: Set authorized key
  tags: user-creation
  ansible.posix.authorized_key:
    user: student
    state: present
    key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAEgEXiWzskC+g+5Va0qtiLi3yiT1UL+ENruRwEgX5FnlknJuKE7NM+6LYccG4MKlgjymbQKN02L7g4E/FRJPJk= student@aspp"
    exclusive: false
  ignore_errors: true

- name: Allow password authentication (Fedora)
  tags: user-creation
  ansible.builtin.copy:
    content: |
      PasswordAuthentication yes

    dest: /etc/ssh/sshd_config.d/80-password-auth.conf
    mode: "0600"
  notify: Reload sshd config

- name: Allow X forwarding (Fedora)
  tags: user-creation
  ansible.builtin.copy:
    content: |
      ForwardX11 yes

    dest: /etc/ssh/ssh_config.d/80-x-forwarding.conf
    mode: "0600"
  notify: Reload sshd config

- name: Set up autologin
  tags: user-creation
  ansible.builtin.copy:
    src: gdm-custom.conf
    dest: /etc/gdm/custom.conf
    mode: "0644"

- name: Create firefox preferences directory
  tags: config
  ansible.builtin.file:
    path: /usr/lib64/firefox/browser/defaults/preferences/
    state: directory
    mode: "0755"

- name: Setup firefox homepage
  tags: config
  ansible.builtin.copy:
    content: |
      pref("browser.startup.homepage", "data:text/plain,browser.startup.homepage=https://aspp.school/wiki/schedule");

    dest: /usr/lib64/firefox/browser/defaults/preferences/firefox-aspp.js
    mode: "0644"

- name: Set timezone to Europe/Berlin
  tags: config
  community.general.timezone:
    name: Europe/Berlin

- name: Add English langpack
  tags: packages
  ansible.builtin.dnf:
    name: glibc-langpack-en

- name: Set language to English
  tags: config
  ansible.builtin.copy:
    content: |
      LANG=en_US.UTF-8
    dest: /etc/locale.conf
    mode: "0644"

- name: Create local unit directory
  tags: config
  ansible.builtin.file:
    path: /usr/local/lib/systemd/user/
    state: directory
    mode: "0755"

- name: Install keyadder service
  tags: config
  ansible.builtin.copy:
    dest: /usr/local/lib/systemd/user/keyadder@.service
    content: |
      [Unit]
      BindsTo=%i.mount

      [Service]
      ExecStart=sh -x -c 'for i in %f/id_*.pub; do ssh-add - <$${i%%.pub}; done'
      ExecStop=ssh-add -D

      Type=oneshot
      RemainAfterExit=true

    mode: "0644"

- name: Create local unit directory
  tags: config
  ansible.builtin.file:
    path: /usr/local/lib/systemd/user/run-media-.mount.d
    state: directory
    mode: "0755"

- name: Install keyadder service
  tags: config
  ansible.builtin.copy:
    dest: /usr/local/lib/systemd/user/run-media-.mount.d/keyadder.conf
    content: |
      [Unit]
      Wants=keyadder@%N.service

    mode: "0644"
