---
- name: Create student user
  tags: user-creation
  ansible.builtin.user:
    name: student
    comment: ASPP Student
    groups: adm, wheel
    password: "{{ common_student_password }}"
    shell: "/bin/bash"

- name: Create itbguest user
  tags: user-creation
  ansible.builtin.user:
    name: itbguest
    comment: itbguest
    groups: adm, wheel
    password: "{{ common_itbguest_password }}"
    shell: "/bin/bash"

- name: ssh | Set authorized keys
  tags: user-creation
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ item.value }}"
    exclusive: false
  ignore_errors: true
  loop: "{{ common_ssh_keys | dict2items }}"

- name: Set up autologin
  tags: user-creation
  ansible.builtin.copy:
    src: gdm-custom.conf
    dest: /etc/gdm/custom.conf
    mode: "0644"
